### PR TITLE
Adds link to good-first-issue label across EDGI

### PR DESCRIPTION
**Pull request by Frijol**
Along the lines of https://github.com/edgi-govdata-archiving/overview/issues/179, to better surface introductory issues!

### CODE REVIEW

**Review by lightandluck — APPROVED** [review]
Cool addition! 👍

**Comment by Mr0grog** [comment]
So I think I said this in the other PR, too, but in Web Monitoring, we have variously had:

- “good-first-issue”
- “first-timer”
- “help-wanted”

But they turned out to all be the same in practice. I don’t add anything except the “help-wanted” label anymore and have been letting the other ones die off as issues get closed. Personally, I much prefer “help-wanted,” but we should go through and change all the “help-wanted” ones if we are going to use something else instead. I have tried to be reasonably diligent about labeling issues with it and giving them at least a little more detailed descriptions (even if I haven’t had time to make them as detailed as would be desired).

**Comment by Frijol** [comment]
@Mr0grog wasn't that resolved in https://github.com/edgi-govdata-archiving/overview/issues/193#issuecomment-453207706 ? I agree that they end up basically the same in practice & am happy to do the standardization (though will need permissions for a lot of the repos, I think mine are per-repo at the moment so can't do all the label work I'd like to :/)

**Comment by Mr0grog** [comment]
I didn’t know anything about that discussion! If people are already agreed on it, ok.

**Comment by lightandluck** [comment]
I brought up the question about this label at a Cross-Team meeting.  Everybody had different preferences, so we consented with going with the default `good-first-issue`. I think it might have been only understood in the context of Archiving/Overview repo and for moving forward on #193. I'm unclear about it now.

We didn't continue the conversation further and talk about all the labels across repos and how to consolidate with WM, which I think is why #193 is still open.

So, Rob you didn't know anything about that broader discussion, because it never happened! 

I propose we bring this up at next Cross-Team and have WM Dev begin to look at the labels in #193 and see what they would add/edit/delete.

**Pull request merged**
