### PR TITLE
Funding info + donate button in the readme

### LINKED ISSUE #229: Put a "Donate" button in the readme?
I'd like to suggest we add, at the bottom of this repo's readme, a footer like:

> *Our work is made possible through volunteer labor, grants, and direct tax-deductible donations from the public.*
> **[Donate to EDGI](https://secure.lglforms.com/form_engine/s/pSsqtc9u4WVkEonQbBbU8Q)** 
> *([More about how EDGI is funded](https://envirodatagov.org/about/how-were-funded/))*

Thoughts on this? Any hesitations? Suggestions for wording changes?

### PR DESCRIPTION
**Pull request by Frijol**
To resolve https://github.com/edgi-govdata-archiving/overview/issues/229

### CODE REVIEW

**Comment by patcon** [comment]
Love this idea! Should we think of it like a websites call-to-action? As in, is there a more active or effective framing for call-to-actions that we should use instead? (Channeling our inner Jimmy Wales, perhaps?)

(this is prob mainly worth being pedantic over if we're thinking about putting it in all the readmes :) )

If so, skimming a doc like this: https://www.canadahelps.org/en/charity-life/fundraising-2/how-and-why-to-include-a-call-to-action-in-your-donor-communications/

> As mentioned above, some of the most effective online CTAs today exist in the form of buttons.

https://shields.io/ ?

> **Double Park Your CTA** [...] By this, we mean that you should always place one of your CTAs above the fold, while the other should be located at the closure of the correspondence.

> **Tracking Your CTA’s** Performance It’s important to start tracking the effectiveness of your online CTAs, if you haven’t yet.

Google Analytics link tracking? The donation page doesn't seem to have an Google Analytics tracking, but perhaps has other tracking. If not, we could perhaps use bit.ly to track click-throughs? Important that this not be locked away in bit.ly where no one would look, but could keep it in a more accessible spreadsheet using https://dev.bitly.com/spreadsheets.html

Could even allow the spreadsheet to be world-readable if we want to make it simple to see the click-through for anyone (without needed privileged access) -- could "hide" the access token inside a function using the "app script" of the spreadsheet, and include that as a custom formula. So a read-only user would only see the formula in the cell that calls for the token, but the token should be concealed. Could also put the whole "fetch the click-through count" logic totally in the "app script", and that would also work.

Anyhow, lemme know if any of this sounds nifty, and I can help if that's of interest :)

**Comment by patcon** [comment]
Also, happy to defer this to elsewhere and not hold up this PR :)

**Comment by Frijol** [comment]
This is cool & something I'd like to explore more! I actually had only intended to put it in this repo's readme, but am curious what folks think about making it part of our standard readme/developing stronger calls to action generally.

Thanks for all the research! I'm going to loop in some folks from Funding and see what they think.

**Comment by Mr0grog** [comment]
> Google Analytics link tracking?

Ha, one of my first thoughts was also “is there a query string or anything we can add to that link that will get tracked?” Bit.ly seems like a great workaround if there’s nothing built-in. I’m not sure we need the whole spreadsheet setup, though, even if it seems pretty nifty.

> https://shields.io/ ?

My first worry there is that folks who spend any significant amount of time on GitHub have been trained to see these a status indicators rather than calls-to-action. Maybe the `popout` style would help it stand out, though. Not sure what iconography would be relevant.

> if we're thinking about putting it in all the readmes :)

That’s probably a good idea, but I feel like the right way to beg for donations in the Readme of a project repo (*especially* in a software/code-focused one) is probably different than what makes sense in the overview repo, so maybe make a separate issue for it so it doesn’t hold up this?

**Comment by Mr0grog** [comment]
> Double Park Your CTA

Oh, maybe shield at top, same kind of descriptive section with link at bottom?

**Pull request merged**
