### PR TITLE
delete gsoc and guidelines folders

### PR DESCRIPTION
**Pull request by Frijol**
Poking around in this repo, these two folders appear outdated.

* We are no longer participating in GSOC
* "Guidelines" contains some useful information but doesn't appear to be present in EDGI members' minds– `project_guidelines.md` wasn't mentioned in the highly relevant https://github.com/edgi-govdata-archiving/overview/issues/170, and there's a PR ~(https://github.com/edgi-govdata-archiving/overview/pull/220) underway~ *merged* that would replace its function. `onboarding.md` largely overlaps with the [Get Involved](https://github.com/edgi-govdata-archiving/overview#get-involved) section of the readme. `community_calls.md` is a set of guidelines for a structure of calls we're not having anymore.

This is my understanding of the situation, but please feel free to voice disagreement!

Suggest that this not merge until https://github.com/edgi-govdata-archiving/overview/pull/220 lands to replace the project_guidelines.

### CODE REVIEW

**Comment by Frijol** [comment]
Alternate idea: pull `project_guidelines` up to top level, update/merge with the ideas in https://github.com/edgi-govdata-archiving/overview/pull/220, possibly rename it (`new_repo_guidelines`) to make it more obvious as a resource?

**Comment by dcwalk** [comment]
I'd hesitate to remove guidelines, even those for things no longer in use, as it can be a helpful pattern/reference for later.

GSOC -- i think we imagined it potentially happening over multiple years, as that isn't what happened. I think archiving important content in the EDGI gdrive and removing the rest from here makes sense

**Comment by lightandluck** [comment]
I was unaware of all these files!

Agree with dcwalk, I think saving these as a pattern would be useful. 

We could put the all the GSoC administration and template files into Gdrive for a rainy day. Don't think there's any reason to keep the proposals.

Merging `project_guidelines` with #220 makes sense. 👍 
The other files in `guidelines` are also nice to keep as patterns. And one of them led me to this [resource](https://github.com/edgi-govdata-archiving/overview/wiki/Resources) which I never knew about either!

**Comment by lightandluck** [comment]
(But, I'm a packrat, so take the above comment with a heaping spoonful of salt)

**Comment by Frijol** [comment]
Thanks for the thoughts! Preserved to Google Drive:

* [Community Calls process](https://docs.google.com/document/d/1GjJ0NdLgW9LpiTwanMe9tFhkmQtHpCZ4E0-96bXd9qk/edit)
* [Onboarding](https://docs.google.com/document/d/1Ab11ovOqUU5CXX74PVVypJ51KcHqelEOMCfpuguB_ac/edit)
* [Project Guidelines](https://docs.google.com/document/d/1EJuy60B_LvJSg-AzhfzGWhycMzsG-lo4tELRYuEROXo/edit) (for good measure, but I will surface most of that doc to the new repo template)
* [GSOC Folder](https://docs.google.com/document/d/1vmySnx43CEuYpvNlodWEd2Q-cBR0BZ7Ix2RAySJW7YY/edit) note that this doc just links to the folder in Github history rather than archiving all content separately

Once https://github.com/edgi-govdata-archiving/overview/pull/220 lands (revised to include better integration with project_guidelines), can this now land & remove the files, or are there still concerns around losing valuable information?

**Comment by Frijol** [comment]
(cc @lightandluck @dcwalk )

**Review by lightandluck — APPROVED** [review]
Agreed, good to go, once #220 is merged 🌟 
Thanks for archiving those notes!

**Pull request merged**
