### PR TITLE
Prep for GSoC application process

### PR DESCRIPTION
**Pull request by dcwalk**
Hey, we've applied, what's next you ask?

- [x] Finalize [ideas summary](https://hackmd.io/BwFgbADBCs0GYFoDMcCcAjBI7sQQ2gFMAmBOAdgGNoqwBGSsY4IA?both#)
- [x] Confirm application procedure (right now: submit a PR to this repo)
- [x] Update files in `gsoc` folder
- [x] Update website: https://envirodatagov.org/gsoc/

### CODE REVIEW

**Comment by titaniumbones** [comment]
am thinking in this case: merge but not close? And maybe merge again later?

**Comment by dcwalk** [comment]
I'm kinda a fan of the dangling PRs ;) Changed to Work In Progress. Would love to merge in by the weekend-end? I think that is realistic

**Comment by dcwalk** [comment]
@titaniumbones -- this is ready for review! Whenever you are happy and merge in I'll get the website page updated

**Comment by titaniumbones** [comment]
I'm merging despite feeling like we should have more ideas up there -- am too tired/stressed to do more on this myself, think @dcwalk should work on other things (actually I just think she should help with more EDGI things, but am pretending to be more generous than that), and really want something to be up and visible, as @dcwalk says

**Comment by dcwalk** [comment]
Agree that we need more! I'm thinking we circle back around and fill these out over time if the GSoC goes ahead? We'll have a much clearer sense of those projects in the next month, which would be before applications open. Tks!

**Comment by titaniumbones** [comment]
Plus 11.  

On February 11, 2017 4:55:38 AM PST, dcwalk <notifications@github.com> wrote:
>Agree that we need more! I'm thinking we circle back around and fill
>these out over time if the GSoC goes ahead? We'll have a much clearer
>sense of those projects in the next month, which would be before
>applications open. Tks!
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/edgi-govdata-archiving/overview/pull/57#issuecomment-279142162

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Pull request merged**
