### PR TITLE
Update code of conduct to link to formally adopted new doc

### PR DESCRIPTION
**Pull request by Frijol**
Pros: All the other repos link to this one doc, which now links to the CoC that's just been adopted.

Cons: Might be a couple of clicks to get to the actual CoC, GDocs has some accessibility issues

### CODE REVIEW

**Comment by lightandluck** [comment]
The document looks really good! Thanks for everyone's work on this 🙏🏽 

• I noticed that the links to the conflict resolution process and toolkits are private. Should that be the case? If so, can we mark them someway or show that they are for EDGI members only? Like "[conflict resolution process (private)](http://link)" or "[conflict resolution process (EDGI members only)](http://link)"?

I get confused when private docs are linked in a public doc. I'm not sure whether I should request access, the doc was linked incorrectly (like there should be a public doc there instead), or I'm just missing out on something.

• Re: too many clicks to get to info - Is it worth porting the doc to this markdown file? Or will keeping them in sync be too much trouble? I can submit a PR to try to do so, but if folks have already decided to keep the single truth in google docs, then we should just go ahead with just linking.

**Comment by patcon** [comment]
> The document looks really good!

💯 ❌  💯 

> If so, can we mark them someway or show that they are for EDGI members only?

Depending on how explicit you want it, I've seen "[some link](#) 🔒" or "[some link](#) 🔒 (members)" used within other orgs. My understanding is that screen-readers can interpret emoji.

</🚲🏠>

> Is it worth porting the doc to this markdown file?

imho your energy required to update a markdown file is way more precious that a handful of users' energy to click an extra click ❤️

**Comment by Mr0grog** [comment]
> > Is it worth porting the doc to this markdown file?
> 
> imho your energy required to update a markdown file is way more precious that a handful of users' energy to click an extra click ❤️

FWIW, I wrote a tool for this a while ago. It’s not perfect, but gets you 90% of the way there pretty quick: https://bafybeialbt7c3ti7kxhxdy2cfmdpjh6o2aupmtvku3vsveoh5p3wnk7qey.ipfs.dweb.link/ (source: https://github.com/Mr0grog/google-docs-to-markdown)

**Comment by Mr0grog** [comment]
That said, I don’t have a huge problem with linking through to the Google doc, but I would additionally update the links in the `README.md` to point straight to the doc, rather than to `CONDUCT.md`.

**Review by lesliealanis — APPROVED** [review]

**Comment by patcon** [comment]
> but I would additionally update the links in the README.md to point straight to the doc, rather than to CONDUCT.md

+1 and maybe an unlinked filler `CONDUCT.md` file to make the little GitHub auto-detect stuff truthy, plus ppl who scan for that visually to suss out project vibes :)

**Comment by Frijol** [comment]
Thanks all! I've adopted the lock emoji in the doc, great idea. I'll see if I can get the Conduct.md to show org-wide via a default community health file (https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file).

Re re-linking the badges, I'm a bit hesitant because I'm worried we'll make a new doc someday and have to relink them all again. Briefly considered making an `envirodatagov.org/conduct` that could redirect but that seems more likely to get lost than this file. Any thoughts on that dilemma?

In the meanwhile, I'll merge so this CoC can be live!

**Comment by Frijol** [comment]
oh jeez, all the badges hard link to the master branch anyway. So I guess I'll go change them all to redirect to main at the very least..

**Comment by Mr0grog** [comment]
> Briefly considered making an `envirodatagov.org/conduct` that could redirect but that seems more likely to get lost than this file. Any thoughts on that dilemma?

What if we had a `<meta http-equiv="refresh" ...>` redirect at `https://edgi-govdata-archiving.github.io/conduct` (or `/overview/conduct`)? That way it would stay managed in GitHub, and maybe be a bit easier to keep in-sync/up-to-date?

**Comment by Mr0grog** [comment]
> all the badges hard link to the master branch anyway

😧

**Pull request merged**
