### PR TITLE
AI wrist watch

### PR DESCRIPTION
**Pull request by Nkongnenwi**
A watch that can automatically detect a change in time zone and respond to it. below is a link of a sample   proposal. 
https://drive.google.com/open?id=0B7bfUwMUs6fhc2t5Qm1tZDN4ODA
I will love to receive a correction on the proposal by mentors of java AI based project. @Rishav159
@Lobby
@redblobgames

### CODE REVIEW

**Comment by dcwalk** [comment]
Hi @Nkongnenwi I'm not sure whether you intended to share your proposal for the EDGI GSoC or another mentoring organization. This doesn't look like it connects with our current projects

**Comment by redblobgames** [comment]
Hi @Nkongnenwi, you mention me and @Rishav159 but we are working on the AIMA GSoC, which is for writing code for the AIMA textbook, not for other AI projects. If you are interested in writing code for the AIMA textbook, please see the [AIMA GSoC ideas page](http://aima.cs.berkeley.edu/gsoc-ideas.html). Or if you are interested in working on edgi-govdata-archiving on web monitoring and change detection, please see the [EDGI GSoC ideas page](https://github.com/edgi-govdata-archiving/overview/blob/master/gsoc/gsoc-ideas.md). The proposal you have written does not seem to be for either of these projects.

**Comment by Nkongnenwi** [comment]
Thanks for the guide so  far in the project, for now i have a test code
based on the book AI the modem approach that i earlier wrote, i don't know
if you can find some time to go through it. to actually know if i
understood the requirement for the a proposal and what i will be doing
through out the summer. below is the link to the code

https://drive.google.com/open?id=0B7bfUwMUs6fhR3hLSDNCeTBlaEE


Best regards

Alain Nkongnenwi

**Comment by redblobgames** [comment]
For GSoC you need to find an organization that has an existing project that you can contribute to. There are hundreds of other organizations listed [here](https://summerofcode.withgoogle.com/organizations/). EDGI (the place you have posted this idea) has a list of projects related to web monitoring and change detection, but nothing related to what you have written in your proposal. AIMA has a list of projects for writing code that's *already in* the AIMA textbook ([there is a of work that needs to be done](http://aima.cs.berkeley.edu/gsoc-ideas.html)), but *not* for code that uses the ideas from the textbook. Once you find an organization that you want to work with, pick a project in that organization and write a proposal for what you will do for that project. There is a guide to writing proposals [here](http://write.flossmanuals.net/gsocstudentguide/writing-a-proposal/) including writing proposals that are not on the project list.

My suggestion:

1. Close this issue — your proposals do not seem to match EDGI's GSoC projects so this github project is not the right place for it.
2. If you want to work on your own ideas, find a GSoC organization that is a good match for your proposal, especially organizations that want ideas that are not already on their own list.
3. If you want to work with AIMA GSoC, look through their list of what work *they* want done.

**Comment by Nkongnenwi** [comment]
Thanks very much for your quick review and correction, i appreciate you for
all your effort but i will love your review  on this other proposal on i
have written on the AI based on the book showing my interest in the project
for GSoC 2017. I believe your correction will be of great help to me and
will be of great help to me.@Rishav159 @Lobby @redblobgames


Regards

Alain Nkongnenwi

**Comment by redblobgames** [comment]
@Nkongnenwi If you are really interested in AIMA GSoC you are posting in the wrong place and you are asking the wrong people. You should go to the AIMA github and gitter chat which are listed on the [AIMA site](http://aima.cs.berkeley.edu/gsoc-ideas.html) and not the EDGI github here. For AIMA-Java, there is a list of needed work [here](https://github.com/aimacode/aima-java/issues).

**Comment by Nkongnenwi** [comment]
Thanks for the Guide

**Comment by dcwalk** [comment]
I'm closing this issue as the deadline has passed.

**Pull request closed without merging**
